apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  # Application settings
  ENVIRONMENT: "production"
  NEXT_PUBLIC_APP_NAME: "TaskFlow"
  NEXT_PUBLIC_AUTHOR: "Asif Ali AstolixGen"
  NEXT_PUBLIC_HACKATHON: "GIAIC Hackathon 2026"
  
  # Backend URL (internal cluster service)
  NEXT_PUBLIC_API_URL: "http://backend-service:8000"
  
  # Email sender info (non-sensitive)
  SENDER_NAME: "TaskFlow"
