apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
  - namespace.yaml
  - configmap.yaml
  # - secret.yaml  # Uncomment after creating from secret.yaml.example
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  app.kubernetes.io/name: taskflow
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/created-by: asif-ali
